---
elasticsearch:
  image: elasticsearch
  ports:
  - "9200:9200"
  - "9300:9300"
logstash:
  image: logstash
  links:
  - elasticsearch:elasticsearch
kibana:
  image: kibana
  links:
  - elasticsearch:elasticsearch
  ports:
  - "5601:5601"
