---
elasticsearch:
  image: elasticsearch
  ports:
  - "9200:9200"
  - "9300:9300"
logstash:
  image: logstash
  ports:
  - "8080:8080"
  links:
  - elasticsearch:elasticsearch
  volumes:
  - "config/logstash/simple.conf:/config/simple.conf:ro"
  command: logstash -f /config/simple.conf
kibana:
  image: kibana
  links:
  - elasticsearch:elasticsearch
  ports:
  - "5601:5601"
